- 1.45.2/alpine3.11/Dockerfile
- 1.45.2/alpine3.12/Dockerfile
- 1.45.2/buster/Dockerfile
- 1.45.2/buster/slim/Dockerfile
- 1.45.2/stretch/Dockerfile
- 1.45.2/stretch/slim/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- Dockerfile-slim.template
Currently if you use the i686 image on an x86_64 host (or armv7 on an aarch64 host) rustup tries to download the x86_64 (or aarch64) binaries. This won't work because the dependencies installed by apt are still i686 (or armv7).
This pr ensures that the arch of the applications installed by rustup always matches the arch of the dependencies installed by apt. No matter the cpu arch this image is running on.
This allows the building of derived images for i686 on x86_64 hosts, and armv7 images on aarch64 hosts.
> Set default_host_triple in rustup config

- 1.48.0/alpine3.11/Dockerfile
- 1.48.0/alpine3.12/Dockerfile
- 1.48.0/buster/Dockerfile
- 1.48.0/buster/slim/Dockerfile
- Dockerfile-alpine.template
- x.py
Adds support for building Alpine images targeting both of the platforms `linux/amd64` and `linux/arm64`, since the blocking issue rust-lang/rustup#2003 recently got resolved.
Necessarily bumps rustup to 1.23.0 since it is the first version to support the aarch64-unknown-linux-musl platform.
Closes: #50
> Add Alpine support for AArch64

- .travis.yml
- 1.61.0/alpine3.14/Dockerfile
- 1.61.0/alpine3.15/Dockerfile
- 1.61.0/bullseye/Dockerfile
- 1.61.0/bullseye/slim/Dockerfile
- 1.61.0/buster/Dockerfile
- 1.61.0/buster/slim/Dockerfile
- x.py
This bumps the version to 1.61.0
Release: https://github.com/rust-lang/rust/releases/tag/1.61.0
> Bump to 1.61.0

- .travis.yml
- 1.61.0/alpine3.16/Dockerfile
- x.py
This patch adds support for the new 3.16 Alpine version to the Rust
docker alpine image. Following the [support policy] suggested in the
3.15 PR, the 3.14 version is removed.
[support policy]: https://github.com/rust-lang/docker-rust/pull/95#discussion_r779944861
> Add Alpine 3.16 support

- .travis.yml
- 1.62.0/alpine3.15/Dockerfile
- 1.62.0/alpine3.16/Dockerfile
- 1.62.0/bullseye/Dockerfile
- 1.62.0/bullseye/slim/Dockerfile
- 1.62.0/buster/Dockerfile
- 1.62.0/buster/slim/Dockerfile
- x.py
This bumps the version to 1.62.0
Release: https://github.com/rust-lang/rust/releases/tag/1.62.0
> Bump to 1.62.0

- .travis.yml
- 1.62.1/1.62.0/alpine3.15/Dockerfile
- 1.62.1/1.62.0/alpine3.16/Dockerfile
- 1.62.1/1.62.0/bullseye/Dockerfile
- 1.62.1/1.62.0/bullseye/slim/Dockerfile
- 1.62.1/1.62.0/buster/Dockerfile
- 1.62.1/1.62.0/buster/slim/Dockerfile
- x.py
This bumps the version to 1.62.1
Release: https://github.com/rust-lang/rust/releases/tag/1.62.1
Blog: https://blog.rust-lang.org/2022/07/19/Rust-1.62.1.html
> Bump to 1.62.1

- .travis.yml
- 1.63.0/alpine3.15/Dockerfile
- 1.63.0/alpine3.16/Dockerfile
- 1.63.0/bullseye/Dockerfile
- 1.63.0/bullseye/slim/Dockerfile
- 1.63.0/buster/Dockerfile
- 1.63.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.63.0 and rustup to 1.25.1
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.63.0
Rustup Release: https://github.com/rust-lang/rustup/releases/tag/1.25.1
Rust Blog: https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html
Rustup Blog: https://blog.rust-lang.org/2022/07/12/Rustup-1.25.1.html
> bump to rust version 1.63.0 and rustup 1.25.1

- .travis.yml
- 1.64.0/alpine3.15/Dockerfile
- 1.64.0/alpine3.16/Dockerfile
- 1.64.0/bullseye/Dockerfile
- 1.64.0/bullseye/slim/Dockerfile
- 1.64.0/buster/Dockerfile
- 1.64.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.64.0
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.64.0
Rust Blog: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html
> bump to rust version 1.64.0

- .travis.yml
- 1.65.0/alpine3.15/Dockerfile
- 1.65.0/alpine3.16/Dockerfile
- 1.65.0/bullseye/Dockerfile
- 1.65.0/bullseye/slim/Dockerfile
- 1.65.0/buster/Dockerfile
- 1.65.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.65.0
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.65.0
Rust Blog: https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html
> bump to rust version 1.65.0

- .travis.yml
- 1.66.0/alpine3.16/Dockerfile
- 1.66.0/alpine3.17/Dockerfile
- 1.66.0/bullseye/Dockerfile
- 1.66.0/bullseye/slim/Dockerfile
- 1.66.0/buster/Dockerfile
- 1.66.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.65.0
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.66.0
Rust Blog: https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html
> bump to rust version 1.66.0

- .travis.yml
- 1.66.1/alpine3.16/Dockerfile
- 1.66.1/alpine3.17/Dockerfile
- 1.66.1/bullseye/Dockerfile
- 1.66.1/bullseye/slim/Dockerfile
- 1.66.1/buster/Dockerfile
- 1.66.1/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.66.1
Rust Blog: https://blog.rust-lang.org/2023/01/10/Rust-1.66.1.html
> bump to rust version 1.66.1

- .travis.yml
- 1.67.0/alpine3.16/Dockerfile
- 1.67.0/alpine3.17/Dockerfile
- 1.67.0/bookworm/Dockerfile
- 1.67.0/bookworm/slim/Dockerfile
- 1.67.0/bullseye/Dockerfile
- 1.67.0/bullseye/slim/Dockerfile
- 1.67.0/buster/Dockerfile
- 1.67.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.67.0
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.67.0
Rust Blog: https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html
> bump to rust version 1.67.0

- 1.67.0/alpine3.16/Dockerfile
- 1.67.0/alpine3.17/Dockerfile
- 1.67.0/bookworm/Dockerfile
- 1.67.0/bookworm/slim/Dockerfile
- 1.67.0/bullseye/Dockerfile
- 1.67.0/bullseye/slim/Dockerfile
- 1.67.0/buster/Dockerfile
- 1.67.0/buster/slim/Dockerfile
- x.py
This bumps the `rustup` version to `1.25.2`. 
Rustup blog: https://blog.rust-lang.org/2023/02/01/Rustup-1.25.2.html
> bump to rustup version 1.25.2

- .travis.yml
- 1.67.1/alpine3.16/Dockerfile
- 1.67.1/alpine3.17/Dockerfile
- 1.67.1/bookworm/Dockerfile
- 1.67.1/bookworm/slim/Dockerfile
- 1.67.1/bullseye/Dockerfile
- 1.67.1/bullseye/slim/Dockerfile
- 1.67.1/buster/Dockerfile
- 1.67.1/buster/slim/Dockerfile
- x.py
This bumps the rust version to 1.67.1
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.67.1
Rust Blog: https://blog.rust-lang.org/2023/02/09/Rust-1.67.1.html
> chore: Bump to rust version 1.67.1

- .travis.yml
- 1.68.0/alpine3.16/Dockerfile
- 1.68.0/alpine3.17/Dockerfile
- 1.68.0/bookworm/Dockerfile
- 1.68.0/bookworm/slim/Dockerfile
- 1.68.0/bullseye/Dockerfile
- 1.68.0/bullseye/slim/Dockerfile
- 1.68.0/buster/Dockerfile
- 1.68.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.68.0`
Rust Blog: https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.68.0
> chore: Bump to rust version 1.68.0

- .travis.yml
- 1.68.1/alpine3.16/Dockerfile
- 1.68.1/alpine3.17/Dockerfile
- 1.68.1/bookworm/Dockerfile
- 1.68.1/bookworm/slim/Dockerfile
- 1.68.1/bullseye/Dockerfile
- 1.68.1/bullseye/slim/Dockerfile
- 1.68.1/buster/Dockerfile
- 1.68.1/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.68.1`
Rust Blog: https://blog.rust-lang.org/2023/03/23/Rust-1.68.1.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.68.1
> chore: Bump to rust version 1.68.1

- .travis.yml
- 1.68.2/alpine3.16/Dockerfile
- 1.68.2/alpine3.17/Dockerfile
- 1.68.2/bookworm/Dockerfile
- 1.68.2/bookworm/slim/Dockerfile
- 1.68.2/bullseye/Dockerfile
- 1.68.2/bullseye/slim/Dockerfile
- 1.68.2/buster/Dockerfile
- 1.68.2/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.68.2`
Rust Blog: https://blog.rust-lang.org/2023/03/28/Rust-1.68.2.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.68.2
> chore: Bump to rust version 1.68.2

- .travis.yml
- 1.69.0/alpine3.16/Dockerfile
- 1.69.0/alpine3.17/Dockerfile
- 1.69.0/bookworm/Dockerfile
- 1.69.0/bookworm/slim/Dockerfile
- 1.69.0/bullseye/Dockerfile
- 1.69.0/bullseye/slim/Dockerfile
- 1.69.0/buster/Dockerfile
- 1.69.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.69.0`
Rust Blog: https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.69.0
> chore: Bump to rust version 1.69.0

- 1.69.0/alpine3.16/Dockerfile
- 1.69.0/alpine3.17/Dockerfile
- 1.69.0/bookworm/Dockerfile
- 1.69.0/bookworm/slim/Dockerfile
- 1.69.0/bullseye/Dockerfile
- 1.69.0/bullseye/slim/Dockerfile
- 1.69.0/buster/Dockerfile
- 1.69.0/buster/slim/Dockerfile
- x.py
This bumps the `rustup` version to `1.26.0`
Rustup Blog: https://blog.rust-lang.org/2023/04/25/Rustup-1.26.0.html
Rustup Release: https://github.com/rust-lang/rustup/releases/tag/1.26.0
Rustup Changelog: https://github.com/rust-lang/rustup/blob/stable/CHANGELOG.md#1260---unreleased
> chore: Bump to `rustup` version 1.26.0

- .travis.yml
- 1.71.0/alpine3.17/Dockerfile
- 1.71.0/alpine3.18/Dockerfile
- 1.71.0/bookworm/Dockerfile
- 1.71.0/bookworm/slim/Dockerfile
- 1.71.0/bullseye/Dockerfile
- 1.71.0/bullseye/slim/Dockerfile
- 1.71.0/buster/Dockerfile
- 1.71.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.71.0`
Rust Blog: https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.71.0
> chore: Bump to rust version 1.71.0

- .travis.yml
- 1.72.0/alpine3.17/Dockerfile
- 1.72.0/alpine3.18/Dockerfile
- 1.72.0/bookworm/Dockerfile
- 1.72.0/bookworm/slim/Dockerfile
- 1.72.0/bullseye/Dockerfile
- 1.72.0/bullseye/slim/Dockerfile
- 1.72.0/buster/Dockerfile
- 1.72.0/buster/slim/Dockerfile
- 1.72.0/trixie/Dockerfile
- 1.72.0/trixie/slim/Dockerfile
- x.py
This PR bumps the Rust version to 1.72.0
- https://github.com/rust-lang/rust/releases/tag/1.72.0
- release note: https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1720-2023-08-24
> Bump to 1.72.0

- .travis.yml
- 1.72.1/alpine3.17/Dockerfile
- 1.72.1/alpine3.18/Dockerfile
- 1.72.1/bookworm/Dockerfile
- 1.72.1/bookworm/slim/Dockerfile
- 1.72.1/bullseye/Dockerfile
- 1.72.1/bullseye/slim/Dockerfile
- 1.72.1/buster/Dockerfile
- 1.72.1/buster/slim/Dockerfile
- x.py
This bumps the Rust version to `1.72.1`
[Rust `1.72.1` announcement blog](https://blog.rust-lang.org/2023/09/19/Rust-1.72.1.html)
[Rust `1.72.1` tagged release](https://github.com/rust-lang/rust/releases/tag/1.72.1)
> chore: Bump to rust version 1.72.1

- .travis.yml
- 1.73.0/alpine3.17/Dockerfile
- 1.73.0/alpine3.18/Dockerfile
- 1.73.0/bookworm/Dockerfile
- 1.73.0/bookworm/slim/Dockerfile
- 1.73.0/bullseye/Dockerfile
- 1.73.0/bullseye/slim/Dockerfile
- 1.73.0/buster/Dockerfile
- 1.73.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.73.0`
Rust Blog: https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.73.0
> chore: Bump to rust version 1.73.0

- .travis.yml
- 1.74.0/alpine3.17/Dockerfile
- 1.74.0/alpine3.18/Dockerfile
- 1.74.0/bookworm/Dockerfile
- 1.74.0/bookworm/slim/Dockerfile
- 1.74.0/bullseye/Dockerfile
- 1.74.0/bullseye/slim/Dockerfile
- 1.74.0/buster/Dockerfile
- 1.74.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.74.0`
Rust Blog: https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.74.0
> chore: Bump to rust version 1.74.0

- .travis.yml
- 1.74.1/alpine3.17/Dockerfile
- 1.74.1/alpine3.18/Dockerfile
- 1.74.1/bookworm/Dockerfile
- 1.74.1/bookworm/slim/Dockerfile
- 1.74.1/bullseye/Dockerfile
- 1.74.1/bullseye/slim/Dockerfile
- 1.74.1/buster/Dockerfile
- 1.74.1/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.74.1`
Rust Blog: https://blog.rust-lang.org/2023/12/07/Rust-1.74.1.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.74.1
> chore: Bump to rust version 1.74.1

- .travis.yml
- 1.75.0/alpine3.17/Dockerfile
- 1.75.0/alpine3.18/Dockerfile
- 1.75.0/bookworm/Dockerfile
- 1.75.0/bookworm/slim/Dockerfile
- 1.75.0/bullseye/Dockerfile
- 1.75.0/bullseye/slim/Dockerfile
- 1.75.0/buster/Dockerfile
- 1.75.0/buster/slim/Dockerfile
- x.py
This bumps the rust version to `1.75.0`
Rust Blog:https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html
Rust Release: https://github.com/rust-lang/rust/releases/tag/1.75.0
> chore: Bump to rust version 1.75.0

- x.py
After talking with @sfackler, it was suggested that I add myself as a maintainer to `x.py` so that I can update the [official image](https://github.com/docker-library/official-images).
> chore: Add `Muscraft` as a maintainer

- .github/workflows/ci.yml
- 1.76.0/alpine3.18/Dockerfile
- 1.76.0/alpine3.19/Dockerfile
- 1.76.0/bookworm/Dockerfile
- 1.76.0/bookworm/slim/Dockerfile
- 1.76.0/bullseye/Dockerfile
- 1.76.0/bullseye/slim/Dockerfile
- 1.76.0/buster/Dockerfile
- 1.76.0/buster/slim/Dockerfile
- x.py
- Release: https://github.com/rust-lang/rust/releases/tag/1.76.0
- Blog: https://blog.rust-lang.org/2024/02/08/Rust-1.76.0.html
> chore: Bump to rust version 1.76.0

- .github/workflows/nightly.yml
- nightly/alpine3.18/Dockerfile
- nightly/alpine3.19/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- nightly/buster/Dockerfile
- nightly/buster/slim/Dockerfile
- x.py
The images for [nightly versions of `rust`](https://hub.docker.com/r/rustlang/rust/), produced by [`rust-lang/docker-rust-nightly`](https://github.com/rust-lang/docker-rust-nightly) have diverged significantly over time, and [recently stopped being published nightly](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Nightly.20docker.20images.20stopped.20updating). Seeing both of these things, it would make sense to move all `rust` related docker images to be managed within one repo. This has the benefit of ensuring we keep the images in sync while having one spot to look at in case of problems.
Merging this PR will not immediately make the nightly images get published from here. We do not have a secret for Docker hub, as well as the images published to …
> feat: Add publishing of nightly Rust versions

- .github/workflows/nightly.yml
This reverts commit 96577a0b83f93cbe1af59e4eaa178b38c37a6ebf. I am doing this because of how we were (and would)       publish to GHCR, which was not the best and ended up not working as I do not have permission to publish.
> Revert "feat: Add publishing to ghcr"

- 1.76.0/alpine3.18/Dockerfile
- 1.76.0/alpine3.19/Dockerfile
- 1.76.0/bookworm/Dockerfile
- 1.76.0/bookworm/slim/Dockerfile
- 1.76.0/bullseye/Dockerfile
- 1.76.0/bullseye/slim/Dockerfile
- 1.76.0/buster/Dockerfile
- 1.76.0/buster/slim/Dockerfile
- nightly/alpine3.18/Dockerfile
- nightly/alpine3.19/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- nightly/buster/Dockerfile
- nightly/buster/slim/Dockerfile
- x.py
This bumps the `rustup` version to `1.27.0`
- [Annoucement Blog](https://blog.rust-lang.org/2024/03/11/Rustup-1.27.0.html)
- [`rustup` Changelog](https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md#1270---2024-03-08)
> chore: Bump to rustup version 1.27.0

- .github/workflows/nightly.yml
And comment it for now, until we get rid of the old image.
> Rename ghcr.io image back to rust-lang/rust

- .github/workflows/ci.yml
- 1.77.0/alpine3.18/Dockerfile
- 1.77.0/alpine3.19/Dockerfile
- 1.77.0/bookworm/Dockerfile
- 1.77.0/bookworm/slim/Dockerfile
- 1.77.0/bullseye/Dockerfile
- 1.77.0/bullseye/slim/Dockerfile
- 1.77.0/buster/Dockerfile
- 1.77.0/buster/slim/Dockerfile
- x.py
Blog: https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html
Release: https://github.com/rust-lang/rust/releases/tag/1.77.0
> chore: Bump to rust version 1.77.0

- .github/workflows/nightly.yml
This should only be merged after we give access to this repo for the `rust-lang/rust` package.
> Restore publishing to ghcr.io

- 1.77.1/alpine3.18/Dockerfile
- 1.77.1/alpine3.19/Dockerfile
- 1.77.1/bookworm/Dockerfile
- 1.77.1/bookworm/slim/Dockerfile
- 1.77.1/bullseye/Dockerfile
- 1.77.1/bullseye/slim/Dockerfile
- 1.77.1/buster/Dockerfile
- 1.77.1/buster/slim/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- Dockerfile-slim.template
- nightly/alpine3.18/Dockerfile
- nightly/alpine3.19/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- nightly/buster/Dockerfile
- nightly/buster/slim/Dockerfile
Hopefully this could help to re-associate the published packages with this repo.
I executed `x.py update` to update the Dockerfiles.
> Add Docker LABEL to associate the built images with the `docker-rust` repository.

- .github/workflows/ci.yml
- 1.77.2/alpine3.18/Dockerfile
- 1.77.2/alpine3.19/Dockerfile
- 1.77.2/bookworm/Dockerfile
- 1.77.2/bookworm/slim/Dockerfile
- 1.77.2/bullseye/Dockerfile
- 1.77.2/bullseye/slim/Dockerfile
- 1.77.2/buster/Dockerfile
- 1.77.2/buster/slim/Dockerfile
- x.py
Blog: https://blog.rust-lang.org/2024/04/09/Rust-1.77.2.html
Release: https://github.com/rust-lang/rust/releases/tag/1.77.2
> chore: Bump to rust version 1.77.2

- .github/workflows/nightly.yml
- 1.77.2/bookworm/Dockerfile
- 1.77.2/bookworm/slim/Dockerfile
- 1.77.2/bullseye/Dockerfile
- 1.77.2/bullseye/slim/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- x.py
Fixes: #197 
Update `x.py` add `s390x` by
```
@@ -21,6 +21,7 @@ debian_arches = [
debian_non_buster_arches = [
DebianArch("ppc64le", "ppc64el", "linux/ppc64le", "powerpc64le-unknown-linux-gnu"),
+    DebianArch("s390x", "s390x", "linux/s390x", "s390x-unknown-linux-gnu"),
]
```
debian_variants = [
then run 
```
python3 x.py update
```
to update docker file
> Add s390x docker build

- .github/workflows/ci.yml
- 1.78.0/alpine3.18/Dockerfile
- 1.78.0/alpine3.19/Dockerfile
- 1.78.0/bookworm/Dockerfile
- 1.78.0/bookworm/slim/Dockerfile
- 1.78.0/bullseye/Dockerfile
- 1.78.0/bullseye/slim/Dockerfile
- 1.78.0/buster/Dockerfile
- 1.78.0/buster/slim/Dockerfile
- x.py
Blog: https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html
Release: https://github.com/rust-lang/rust/releases/tag/1.78.0
> chore: Bump to rust version 1.78.0

- .github/workflows/ci.yml
- 1.79.0/alpine3.19/Dockerfile
- 1.79.0/alpine3.20/Dockerfile
- 1.79.0/bookworm/Dockerfile
- 1.79.0/bookworm/slim/Dockerfile
- 1.79.0/bullseye/Dockerfile
- 1.79.0/bullseye/slim/Dockerfile
- 1.79.0/buster/Dockerfile
- 1.79.0/buster/slim/Dockerfile
- x.py
- [Blog](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html)
- [Release](https://github.com/rust-lang/rust/releases/tag/1.79.0)
> chore: Bump to rust version 1.79.0

- 1.79.0/alpine3.19/Dockerfile
- 1.79.0/alpine3.20/Dockerfile
- 1.79.0/bookworm/Dockerfile
- 1.79.0/bookworm/slim/Dockerfile
- 1.79.0/bullseye/Dockerfile
- 1.79.0/bullseye/slim/Dockerfile
- 1.79.0/buster/Dockerfile
- 1.79.0/buster/slim/Dockerfile
- nightly/alpine3.19/Dockerfile
- nightly/alpine3.20/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- nightly/buster/Dockerfile
- nightly/buster/slim/Dockerfile
- x.py
This bumps the `rustup` version to `1.27.1`
- [Annoucement Blog](https://blog.rust-lang.org/2024/05/06/Rustup-1.27.1.html)
- [`rustup` Changelog](https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md#1271---2024-04-14)
> chore: Bump to rustup version 1.27.1

- .github/workflows/ci.yml
- 1.80.0/alpine3.19/Dockerfile
- 1.80.0/alpine3.20/Dockerfile
- 1.80.0/bookworm/Dockerfile
- 1.80.0/bookworm/slim/Dockerfile
- 1.80.0/bullseye/Dockerfile
- 1.80.0/bullseye/slim/Dockerfile
- x.py
Rust version 1.80.0 is out!
- [Blog](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html)
- [Release](https://doc.rust-lang.org/nightly/releases.html#version-1800-2024-07-25)
> Bump to rust version 1.80.0

- .github/workflows/ci.yml
- 1.80.1/alpine3.19/Dockerfile
- 1.80.1/alpine3.20/Dockerfile
- 1.80.1/bookworm/Dockerfile
- 1.80.1/bookworm/slim/Dockerfile
- 1.80.1/bullseye/Dockerfile
- 1.80.1/bullseye/slim/Dockerfile
- x.py
- [Blog](https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html)
- [Tag](https://github.com/rust-lang/rust/releases/tag/1.80.1)
> chore: Bump to rust version 1.80.1

- .github/workflows/ci.yml
- 1.81.0/alpine3.19/Dockerfile
- 1.81.0/alpine3.20/Dockerfile
- 1.81.0/bookworm/Dockerfile
- 1.81.0/bookworm/slim/Dockerfile
- 1.81.0/bullseye/Dockerfile
- 1.81.0/bullseye/slim/Dockerfile
- x.py
Rust Version 1.81 has been released!
https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html
> Update Rust version to 1.81.0 

- .github/workflows/nightly.yml
- 1.81.0/bullseye/Dockerfile
- 1.81.0/bullseye/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- x.py
[Debian Bullseye entered LTS recently](https://wiki.debian.org/LTS/Bullseye), which means `ppc64el` and `s390x` are no longer supported architectures. This PR removes `ppc64el` and `s390x` from `bullseye`.
> fix: Remove non-LTS arches from bullseye

- .github/workflows/ci.yml
- stable/alpine3.19/Dockerfile
- stable/alpine3.20/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
[1.82.0 Release](https://github.com/rust-lang/rust/releases/tag/1.82.0)
[Announcement Blog](https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html)
> chore: Bump to rust version 1.82.0

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
[1.84.0 Release](https://github.com/rust-lang/rust/releases/tag/1.84.0)
[Announcement Blog](https://blog.rust-lang.org/2025/01/09/Rust-1.84.0.html)
> chore: Bump to rust version 1.84.0

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
https://github.com/rust-lang/rust/releases/tag/1.84.1
https://blog.rust-lang.org/2025/01/30/Rust-1.84.1.html
> chore: Bump to rust version 1.84.1

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
Pre-making this PR :) Links won't work till 02/20
https://github.com/rust-lang/rust/releases/tag/1.85.0
https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html
> chore: Bump to rust version 1.85.0

- .github/workflows/nightly.yml
reverts #226 as https://github.com/docker/setup-qemu-action/issues/198 has been fixed
> chore(ci): Revert temporary workaround for ARM builds

- nightly/alpine3.20/Dockerfile
- nightly/alpine3.21/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
https://github.com/rust-lang/rustup/blob/stable/CHANGELOG.md#1280---2025-03-04
> chore: Bump to rustup version 1.28.0

- nightly/alpine3.20/Dockerfile
- nightly/alpine3.21/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
https://blog.rust-lang.org/2025/03/04/Rustup-1.28.1.html
https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md#1281---2025-03-05
> chore: Bump to rustup version 1.28.1

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
https://blog.rust-lang.org/2025/03/18/Rust-1.85.1.html
https://github.com/rust-lang/rust/releases/tag/1.85.1
> chore: Bump to rust version 1.85.1

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
- https://github.com/rust-lang/rust/releases/tag/1.86.0
- https://blog.rust-lang.org/2025/04/03/Rust-1.86.0.html
> chore: Bump to rust version 1.86.0

- LICENSE-APACHE
- LICENSE-MIT
- README.md
There is an open issue regarding this (resolve #12) and the latest statement of one of the contributers pointed towards a MIT license. However, I copied the license statement from another repository of rust-lang (https://github.com/rust-lang/rust-clippy) because I expect this to be compliant with the general licensing strategy of rust-lang. 
I set the copyright to "Copyright 2017-2021 The Rust Project Developers" as these are the dates of the first and latest commit in this repository.
Please let me know if can improve anything. I don't want to pressure the rust-lang community into publishing this with the proposed licenses. I hope that the license issue can be closed soon, tho. Have a nice day, and thank you for reviewing this PR!
> Adding License Statement (MIT and Apache)

- nightly/alpine3.20/Dockerfile
- nightly/alpine3.21/Dockerfile
- nightly/bookworm/Dockerfile
- nightly/bookworm/slim/Dockerfile
- nightly/bullseye/Dockerfile
- nightly/bullseye/slim/Dockerfile
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
Blog: https://blog.rust-lang.org/2025/05/05/Rustup-1.28.2/
> chore: Update rustup to 1.28.2

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
https://github.com/rust-lang/rust/releases/tag/1.87.0
https://blog.rust-lang.org/2025/05/15/Rust-1.87.0.html
> chore: Bump to rust version 1.87.0

- .github/workflows/ci.yml
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/alpine3.22/Dockerfile
- stable/bookworm/Dockerfile
- stable/bookworm/slim/Dockerfile
- stable/bullseye/Dockerfile
- stable/bullseye/slim/Dockerfile
- x.py
https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/
https://github.com/rust-lang/rust/releases/tag/1.88.0
> chore: Bump to Rust version 1.88.0

- .github/workflows/nightly.yml
- nightly/alpine3.20/Dockerfile
- nightly/alpine3.21/Dockerfile
- nightly/alpine3.22/Dockerfile
- stable/alpine3.20/Dockerfile
- stable/alpine3.21/Dockerfile
- stable/alpine3.22/Dockerfile
- x.py
powerpc64le-unknown-linux-musl is a tier 2 with host tools target since 1.85.0, which lets us add support for ppc64le to the Alpine Linux images.
> Add Alpine ppc64le images

- .github/workflows/nightly.yml
- x.py
[Debian Trixie](https://www.debian.org/releases/trixie/) was officially released on `2025-08-09`, making it the newest stable Debian version. Since that is the case, I made it the "default" Debian version.
> chore: Make Trixie the default debian version
